### ISSUE TITLE
Poll doesn't show

### ISSUE THREAD

**Issue by Chielclaes** [nickv-nextcloud/talk_simple_poll#12]
When i made the poll as in the readme file i'm not getting a poll just a chathead whitout text.
![afbeelding](https://user-images.githubusercontent.com/58774515/81583195-46877b80-93b1-11ea-856c-9d23d63d9079.png)

**Comment by nickvergessen** [comment]
Works fine here.
Can you check if there is something in the log file?

Also in Talk 8.0.4 the commands changed a bit, so you might want to check if your commands match https://github.com/nickv-nextcloud/talk_simple_poll#installation
