### ISSUE TITLE
Useability

### ISSUE THREAD

**Issue by NotReallyNotNotMe** [nickv-nextcloud/talk_simple_poll#28]
My comments are meant to help make the app more user friendly.
1. Adding time for a date - roll downs are tedious to use. Provide a box to type in time and date without having to play with rolling selection.
2. Very hard to add a new date. I click on the calendar/plus option, nothing happened.
3. Sharing - make it so one can select multiple attendees from the contact list rather than having to type in each name, and then clicking on Send invitation mail. Too many key strokes. One should be able to mail to all at once using a pick list from contacts. Make it so send goes to all. Yes, I know one can select a group but that does not apply when the share list varies.
4. If a date is entered by mistake, hard to find how to delete that entry. Provide a delete button.
5. Have a delete option for a poll rather than needed to archive, delete, etc. Or, at least make it  an option on the three-dot menu drop down. (Yes, I have seen the counter argument. Make it user friendly.)

For the above reasons, I am unlikely to make simple poll a go-to app.

Thanks for the efforts.

/Roger

**Comment by nickvergessen** [comment]
I think you posted to the wrong app. This app is only a demo app for inside the chat of Nextcloud Talk

It does not have dates nor a user list or something. Only chat messages

**Comment by nickvergessen** [comment]
Please open your issue in https://github.com/nextcloud/polls
