### ISSUE TITLE
Slight wording improvements and cuts

### ISSUE THREAD

**Issue by jancborchardt** [nickv-nextcloud/talk_simple_poll#6]
Currently:
```
Poll: Do you like polls?
100 votes have been casted

1. Yes
████████████████████████████████████████████████░░ 96% (Votes: 96)
2. No
██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 4% (Votes: 4)
```

Proposal:
```
**Do you like polls?** 100 people voted:

1. Yes
████████████████████████████████████████████████░░ 96 votes, 96%
2. No
██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 4 votes, 4%
```

(If bolding is possible. And then it would also be good to bold the winning vote, or maybe show a ⭐ or 🏆 emoji next to it.)

**Comment by nickvergessen** [comment]
Bold is not possible atm, until https://github.com/nextcloud/spreed/issues/1027

Still put asterixes around the question?

**Comment by jancborchardt** [comment]
Until bolding is possible we can simply do without the bolding, and without the asterisks too as it looks much simpler. :)

**Comment by nickvergessen** [comment]
Done with https://github.com/nickv-nextcloud/talk_simple_poll/commit/d19e519a1e0832fb64bc76cfd32abb0916a65d78
