### ISSUE TITLE
The process control (PCNTL) extensions are required in case you want to interrupt long running commands

### ISSUE THREAD

**Issue by WNYmathGuy** [nickv-nextcloud/talk_simple_poll#8]
So each time a poll launches or a vote is cast, this message prepends it:
```
The process control (PCNTL) extensions are required in case you want to interrupt 
long running commands - see http://php.net/manual/en/book.pcntl.php
```
My PHP.ini file has this:
```
; This directive allows you to disable certain functions for security reasons.
; It receives a comma-delimited list of function names.
; http://php.net/disable-functions
disable_functions = pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_get_handler,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,pcntl_async_signals,
```

I'm not sure I want to enable things said to be disabled for security reasons, but I also don't want that message each time a poll is in process.

Can I disable the message?

**Comment by nickvergessen** [comment]
Well, as you can read in the message, the extension allows you to stop long running commands. So yeah, since you want to use CLI this way, it's okay to enable/allow those functions.

**Comment by WNYmathGuy** [comment]
I'm very novice with PHP. I couldn't find a definite `enable_functions` or a `allow_functions` so I just commented out the line for the `PHP.ini` of the Nextcolud's virtual server. That did the trick.
